### ISSUE TITLE
New Branch or New Branch

### ISSUE THREAD

**Issue by ddutchie** [VirtualEngineeringLab/Pathtracing#1]
Hello There. 

This is a clever hack and I managed to integrate it into my unity path-tracer also based off of David's.

However mine also has mesh support,  acceleration structures and some other pretty awesome hacky things. It works really well, but could do with some refactoring. 

One thing I am proud of is a hybrid approach for texture sampling.
I sample the gbuffer for color and normal calcs instead of feeding texture data to gpu.
I have also integrated transparency and refraction.

Its too different to make a pull request, but I believe there are some things there for you to also benefit from. 

Let me know...

**Comment by ddutchie** [comment]
Start here for acceleration structures
https://github.com/pieroaccardi/Unity_PathTracing

Some of my modification here:
https://github.com/ddutchie/Unity_PathTracing

**Comment by WilliamSokolErhard** [comment]
I made the `ExperimentalAccelerationStructures` branch to work on this. I have this now integrated at runtime into the main scene. It works in VR and even can be used in one eye with the existing solution in the other.

The problem is that all the shading and current sphere generation and all my additions are currently incompatible without digging and piecing together the compute shaders. I'll see if I can do some more work to tie them together but I can't just rip out singular components and plug them in easily.
